### PR TITLE
Solves #24

### PR DESCRIPTION
**Pull request by LOK-Soft**

### CODE REVIEW

**Comment by elboletaire** [comment]
I need to check it, but apparently LGTM

Thanks for your contribution.

**Comment by LOK-Soft** [comment]
FYI:
In order to have compatible code the change will not cause any behavior change when updating this script. Only there is an new option "historyOnInit" available, you can set to false to disable the hash on initialisation.

**Comment by elboletaire** [comment]
Please, don't update the version numbers. That's something must be done in master.

BTW, I'll try to add some scripts like in https://github.com/elboletaire/password-strength-meter to automatically update them, so, please, undo that changes.

Apart from that everything looks good :)

**Comment by elboletaire** [comment]
Fixed in dfe100f3784194e7b98e58429c43f0845b547429

**Pull request closed without merging**
